AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

# we need to test the #each method directly
Style/MapIntoArray:
  Exclude:
    - 'spec/cookie_file_spec.rb'
